
CLIENT_HELLO = "CLIENT_HELLO"
SERVER_HELLO = "SERVER_HELLO"
HANDSHAKE_FINISH = "HANDSHAKE_FINISH"

PING = "PING"
PONG = "PONG"
ERROR = "ERROR"

LIST_FILES_REQUEST = "LIST_FILES_REQUEST"
LIST_FILES_RESPONSE = "LIST_FILES_RESPONSE"

GET_FILE_REQUEST = "GET_FILE_REQUEST"
GET_FILE_RESPONSE = "GET_FILE_RESPONSE"

FILE_CHUNK = "FILE_CHUNK"
FILE_TRANSFER_COMPLETE = "FILE_TRANSFER_COMPLETE"

# Consent protocol
FILE_REQUEST = "FILE_REQUEST"
FILE_REQUEST_ACCEPT = "FILE_REQUEST_ACCEPT"
FILE_REQUEST_DENY = "FILE_REQUEST_DENY"

# Key migration
KEY_MIGRATION = "KEY_MIGRATION"

# Manifest exchange (for offline redistribution)
MANIFEST_REQUEST = "MANIFEST_REQUEST"
MANIFEST_RESPONSE = "MANIFEST_RESPONSE"

PROTOCOL_VERSION = "1.0"
